name: Check

on:
  pull_request:

  push:
    branches:
      - 2.8.x # Check 2.8.x branch after merge

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-local:
    name: Publish local
    uses: playframework/.github/.github/workflows/cmd.yml@v2
    with:
      java: 11, 8
      scala: 2.13.8, 2.12.15
      cmd: sbt ++$MATRIX_SCALA publishLocal # Check that we can actually build and package the library

  finish:
    name: Finish
    needs: # Should be last
      - "publish-local"
    uses: playframework/.github/.github/workflows/rtm.yml@v2
